name: build
on:
  push:
    branches:
      - main

jobs:
  build_for_pypi:
    if: ${{ github.event.repository.name != 'ccxt-python-single-exchange' && contains(github.event.head_commit.message, '[BUILD]') }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.ref }}
          persist-credentials: false
      # - name: Install npm & tsx
      #   uses: actions/setup-node@v4
      #   with:
      #     node-version: '22'
      #     cache: 'npm'
      # - name: Cache npm dependencies
      #   uses: actions/cache@v3
      #   with:
      #     path: ~/.npm
      #     key: ${{ runner.os }}-npm-${{ hashFiles('**/package.json') }}
      #     restore-keys: |
      #       ${{ runner.os }}-npm-
      # - name: Install dependencies
      #   run: |
      #     cd build
      #     npm install typescript
      #     npm install tsx
      - name: Build
        run: |
          cd build || echo "already in build"
          # get repository name and it's first word before hypher and pass that as argument
          REPO_NAME=$(echo ${{ github.repository }} | cut -d'/' -f2 | cut -d'-' -f1)
          echo "REPO_NAME: $REPO_NAME"
          npm run build -- $REPO_NAME

      - name: Commit and push changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add README.md
          git commit -m "Update README with exchange repository links" || echo "No changes to commit"
          git push